{{- if eq .Values.storage.provider "minio" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiclaw.minio.fullname" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.component.labels" (dict "root" . "component" "minio") | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.storage.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.storage.minio.auth.rootPassword | quote }}
{{- end }}
