{{- if eq .Values.storage.provider "minio" }}
{{- $comp := dict "root" . "component" "minio" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiclaw.minio.fullname" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.component.labels" $comp | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "hiclaw.component.selectorLabels" $comp | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.storage.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.storage.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
{{- end }}
